version: 561

branches:
  only:
    - master

skip_tags: true
image: Visual Studio 2019

clone_folder: c:\projects\less-Windows

build_script: build.py

artifacts:

  path: c:\projects\less-Windows
    name: less.exe
  path: c:\projects\less-Windows
    name: lesskey.exe

deploy:

  provider: GitHub
   artifact: /.*\.exe/
   draft: true
   on:
    branch: master
