version: 561.1

branches:
  only:
    - master

skip_tags: true
image: Visual Studio 2019

clone_folder: c:\projects\less-Windows

build_script: build.py

artifacts:
  - path: c:\projects\less-Windows\less.exe


deploy:

  provider: GitHub
   artifact: /.*\.exe/
   draft: true
   on:
    branch: master
