version: 561.{build}

branches:
  only:
    - master

skip_tags: true
image: Visual Studio 2019

clone_folder: c:\projects\less-Windows

before_build: version_compare.py

build_script: build.py

artifacts:
  - path: less.exe
  - path: lesskey.exe

deploy:
  release: less-v$(appveyor_build_version)
  provider: GitHub
  artifact: /.*\.exe/
  draft: true
  auth_token:
    secure: VlfBv4xKonkDXe8nD0wW5UZQd7CYNQj5Nl+Xvpk6mwwwh8rmQED8jOXfdpYWKK4v
  on:
    branch: master
