version: 561

branches:
  only:
    - master

skip_tags: true
image: Visual Studio 2019

clone_folder: c:\projects\less-Windows

build_script: build.py

deploy:
   provider: GitHub
   artifact: /.*\.exe/
   draft: true
   on:
    branch: master
